# arch: arm64-graviton2
# virt: lxd
# os: linux
# dist: focal
language: java
cache:
  directories:
  - "$HOME/.cache"

install:
- git clone https://${GITHUB_TOKEN}@github.com/javaf/deploy "$HOME/deploy"
- chmod 777 "$HOME/deploy/"*.sh
- bash "$HOME/deploy/install.sh"

script:
- bash "$HOME/deploy/script.sh"
